# Generated by Django 2.1.4 on 2018-12-08 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=30)),
                ('comuna', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormaTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=60)),
                ('fecha', models.DateField(default=datetime.datetime(2018, 12, 8, 21, 22, 19, 395565, tzinfo=utc))),
                ('horaini', models.DateTimeField(blank=True, null=True)),
                ('horater', models.DateTimeField(blank=True, null=True)),
                ('numasc', models.IntegerField(default=0)),
                ('modeloasc', models.CharField(max_length=30)),
                ('fallas', models.CharField(max_length=200)),
                ('reparacion', models.CharField(max_length=200)),
                ('piezas', models.CharField(max_length=200)),
                ('tecnico', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
