# Generated by Django 2.1.4 on 2018-12-08 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatrabajo',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2018, 12, 8, 21, 25, 12, 643844, tzinfo=utc)),
        ),
    ]
