# Generated by Django 2.1.4 on 2018-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantencion', '0002_auto_20181208_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatrabajo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
